//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("More.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested range for the specified media resource is not satisfiable. When specified, the range for the requested media resource must be 0 - {0:N0} and the From index must be less than the To index..
        /// </summary>
        internal static string ControllerRangeNotSatisfiable {
            get {
                return ResourceManager.GetString("ControllerRangeNotSatisfiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requests are not supported..
        /// </summary>
        internal static string ControllerUnsupportedMethod {
            get {
                return ResourceManager.GetString("ControllerUnsupportedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type &apos;{0}&apos; cannot be configured as an annotation because it&apos;s a collection. Use the HasAnnotations method for annotation collections..
        /// </summary>
        internal static string InvalidComplexType {
            get {
                return ResourceManager.GetString("InvalidComplexType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type &apos;{0}&apos; cannot be configured as an annotation because collections of collections is not supported..
        /// </summary>
        internal static string InvalidComplexTypeCollection {
            get {
                return ResourceManager.GetString("InvalidComplexTypeCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; cannot be configured as an annotation more than once..
        /// </summary>
        internal static string MultipleAnnotationConfigsNotAllowed {
            get {
                return ResourceManager.GetString("MultipleAnnotationConfigsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified seek offset and origin must result in a position that is greater than or equal to zero and less than the length of the stream..
        /// </summary>
        internal static string SeekOffsetOutOfRange {
            get {
                return ResourceManager.GetString("SeekOffsetOutOfRange", resourceCulture);
            }
        }
    }
}
